# See https://www.nextflow.io/docs/latest/process.html#script for the difference
# between NextFlow and Bash variables.
venv_path = "\\$HOME/venv37-ocrd/bin/activate"

workspace_path = "$projectDir/ocrd-workspace/"
mets_path = "$projectDir/ocrd-workspace/mets.xml"