workspace_path = "$projectDir/ocrd-workspace/"
mets_path = "$projectDir/ocrd-workspace/mets.xml"

# Dockerized parameters
docker_pwd = "/ocrd-workspace"
docker_image = "ocrd/all:maximum"
docker_models_dir = "/usr/local/share/ocrd-resources"

# See https://www.nextflow.io/docs/latest/process.html#script for the difference
# between NextFlow and Bash variables.
venv_path = "\\$HOME/venv37-ocrd/bin/activate"
models_path = "\\$HOME/ocrd_models"
